# -*- coding: utf-8 -*-
"""GenAI_silver_badge_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JBEVLSbXGXWvSANFW228Of3GeuS0s0JZ

# **AI Recipe Recommendation Engine**
"""

!pip install -q pandas scikit-learn sentence-transformers gradio

import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import gradio as gr

recipes = pd.DataFrame({

    "Recipe": [
        "Veg Pasta",
        "Chicken Curry",
        "Paneer Salad",
        "Omelette",
        "Fruit Smoothie",
        "Veg Fried Rice",
        "Grilled Fish",
        "Tomato Soup"
    ],

    "Ingredients": [
        "pasta tomato cheese onion garlic",
        "chicken onion tomato garlic spices",
        "paneer cucumber tomato lettuce",
        "egg onion cheese pepper",
        "banana milk honey apple",
        "rice carrot beans onion soy sauce",
        "fish lemon garlic butter",
        "tomato onion garlic cream"
    ],

    "Diet": [
        "vegetarian",
        "non-vegetarian",
        "vegetarian",
        "non-vegetarian",
        "vegetarian",
        "vegetarian",
        "non-vegetarian",
        "vegetarian"
    ],

    "Skill": [
        "beginner",
        "intermediate",
        "beginner",
        "beginner",
        "beginner",
        "intermediate",
        "advanced",
        "beginner"
    ],

    "Calories": [
        450,
        650,
        300,
        250,
        180,
        400,
        500,
        220
    ],

    "CookingTime": [
        "20 mins",
        "45 mins",
        "15 mins",
        "10 mins",
        "5 mins",
        "30 mins",
        "40 mins",
        "15 mins"
    ]
})

recipes

model = SentenceTransformer('all-MiniLM-L6-v2')

recipe_embeddings = model.encode(recipes["Ingredients"].tolist())

def recommend_recipe(user_ingredients, diet, skill):

    # Convert user input into embedding
    user_embedding = model.encode([user_ingredients])

    # Similarity score
    similarities = cosine_similarity(user_embedding, recipe_embeddings)[0]

    recipes["Similarity"] = similarities

    # Filter by diet + skill
    filtered = recipes[
        (recipes["Diet"] == diet) &
        (recipes["Skill"] == skill)
    ]

    if filtered.empty:
        return "No matching recipes found."

    # Sort by similarity
    filtered = filtered.sort_values(
        by="Similarity",
        ascending=False
    )

    # Top 3 recipes
    top_recipes = filtered.head(3)

    output = ""

    for _, row in top_recipes.iterrows():

        output += f"""
🍽 Recipe: {row['Recipe']}

🧂 Ingredients:
{row['Ingredients']}

🔥 Calories:
{row['Calories']}

⏱ Cooking Time:
{row['CookingTime']}

-----------------------------------
"""

    return output

days = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
]


def generate_meal_plan(diet, skill):

    filtered = recipes[
        (recipes["Diet"] == diet) &
        (recipes["Skill"] == skill)
    ]

    if len(filtered) == 0:
        return "No recipes available."

    meal_plan = ""

    selected_recipes = filtered.sample(
        n=min(7, len(filtered)),
        replace=True
    )

    for day, (_, row) in zip(days, selected_recipes.iterrows()):

        meal_plan += f"""
📅 {day}

🍽 Meal: {row['Recipe']}
🔥 Calories: {row['Calories']}
⏱ Time: {row['CookingTime']}

-----------------------------
"""

    return meal_plan

def generate_shopping_list(diet, skill):

    filtered = recipes[
        (recipes["Diet"] == diet) &
        (recipes["Skill"] == skill)
    ]

    ingredients = []

    for item in filtered["Ingredients"]:

        split_items = item.split()

        ingredients.extend(split_items)

    unique_ingredients = sorted(set(ingredients))

    shopping_list = "\n".join(
        [f"🛒 {item}" for item in unique_ingredients]
    )

    return shopping_list

# Recipe Recommendation Interface
recipe_interface = gr.Interface(

    fn=recommend_recipe,

    inputs=[
        gr.Textbox(
            label="Ingredients",
            placeholder="tomato onion cheese"
        ),

        gr.Dropdown(
            ["vegetarian", "non-vegetarian"],
            label="Diet Preference"
        ),

        gr.Dropdown(
            ["beginner", "intermediate", "advanced"],
            label="Cooking Skill"
        )
    ],

    outputs="text",

    title="🍳 Recipe Recommendation Engine"
)


# Weekly Meal Planner Interface
meal_interface = gr.Interface(

    fn=generate_meal_plan,

    inputs=[
        gr.Dropdown(
            ["vegetarian", "non-vegetarian"],
            label="Diet Preference"
        ),

        gr.Dropdown(
            ["beginner", "intermediate", "advanced"],
            label="Cooking Skill"
        )
    ],

    outputs="text",

    title="📅 Weekly Meal Planner"
)


# Shopping List Interface
shopping_interface = gr.Interface(

    fn=generate_shopping_list,

    inputs=[
        gr.Dropdown(
            ["vegetarian", "non-vegetarian"],
            label="Diet Preference"
        ),

        gr.Dropdown(
            ["beginner", "intermediate", "advanced"],
            label="Cooking Skill"
        )
    ],

    outputs="text",

    title="🛒 Shopping List Generator"
)


# Combine all tabs
app = gr.TabbedInterface(

    [
        recipe_interface,
        meal_interface,
        shopping_interface
    ],

    [
        "Recipe Recommender",
        "Meal Planner",
        "Shopping List"
    ]
)

app.launch()